version: "3"


services:

  owl:
    image: nmap-app-owl
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"

  ostrich:
    image: nmap-app-ostrich
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6001:6001"

  db_pg:
    image: postgres:9.3.6
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_USER: "golang"
      POSTGRES_DB: "golang"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql

  db_redis:
    image: redis:4.0.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis
    volumes:
      - ./data/redis:/data

  db_rabbit:
    image: rabbitmq:3.6-management-alpine
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.6
      RABBITMQ_ERLANG_COOKIE: "erlangcookie"
      RABBITMQ_DEFAULT_USER: "rabbituser"
      RABBITMQ_DEFAULT_PASS: "rabbitpassword"
    ports:
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
