version: '3'


services:

  db_pg:
    image: postgres:9.6.5-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  db_redis:
    image: redis:4.0.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - ./data/redis:/data

  db_rabbit:
    image: rabbitmq:3.6-management-alpine
    hostname: ${RABBITMQ_NODENAME}
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: ${RABBITMQ_VM_MEMORY_HIGH_WATERMARK}
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

  ostrich:
    image: nmap-app-ostrich
    ports:
      - '${OSTRICH_PORT}:${OSTRICH_PORT}'
    command: flask run -p ${OSTRICH_PORT} --host=0.0.0.0
    depends_on:
      - db_pg
      - db_redis
      - db_rabbit
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_QUEUE: ${RABBIT_QUEUE}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  owl:
    image: nmap-app-owl
    ports:
      - '${OWL_PORT}:${OWL_PORT}'
    command: flask run -p ${OWL_PORT} --host=0.0.0.0
    depends_on:
      - db_pg
      - db_redis
      - db_rabbit
      - ostrich
    environment:
      OSTRICH_HOST: ${OSTRICH_HOST}
      OSTRICH_PORT: ${OSTRICH_PORT}
      OWL_TARGET_FILE: ${OWL_TARGET_FILE}
